# Generated by Django 4.2.5 on 2023-10-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cooking_tiime', models.IntegerField(help_text='In Minutes')),
                ('ingredients', models.CharField(help_text='Ingredients must be separated by commas.', max_length=255)),
            ],
        ),
    ]
